### ISSUE TITLE
Unconfigured icons

### ISSUE THREAD

**Issue by thytetgc** [alseambusher/crontab-ui#82] opened 2018-08-03 15:39 UTC
_Last installed version
Ubuntu 18 updated_

I can not make the icons any better

[https://uploaddeimagens.com.br/images/001/543/521/original/Sem_título.png](url)

**Comment by alseambusher** [comment] 2018-11-02 22:55
I think the link is broken and I do not get what the issue is. I will close the issue for now. If you feel that something has to change, please feel free to reopen it.

**Closed by alseambusher** 2018-11-02 22:55 UTC
